
version: 2

models:
  - name: taxi_trips
    description: "Information about taxi trips"
    columns:
      - name: pickup
        description: "Pickup Time"
      - name: dropoff
        description: "Dropoff Time"
      - name: passengers
        description: "Number of Passangers"
      - name: distance
        description: "Distance"
      - name: fare
        description: "Fare"
      - name: tip
        description: "Tip"
      - name: tolls
        description: "Tolls"
      - name: total
        description: "Total"
      - name: color
        description: "Color"
      - name: payment
        description: "Payment Method"
      - name: pickup_zone
        description: "Pickup Zone"
      - name: dropoff_zone
        description: "Dropoff Zone"
      - name: pickup_borough
        description: "Pickup Borough"
      - name: dropoff_borough
        description: "Dropoff Borough"
        
  - name: over_nine_miles
    description: "Trips that were longer than 9 miles"
    columns:
      - name: pickup
        description: "Pickup Time"
      - name: dropoff
        description: "Dropoff Time"
      - name: passengers
        description: "Number of Passangers"
      - name: distance
        description: "Distance"
      - name: fare
        description: "Fare"
      - name: tip
        description: "Tip"
      - name: tolls
        description: "Tolls"
      - name: total
        description: "Total"
      - name: color
        description: "Color"
      - name: payment
        description: "Payment Method"
      - name: pickup_zone
        description: "Pickup Zone"
      - name: dropoff_zone
        description: "Dropoff Zone"
      - name: pickup_borough
        description: "Pickup Borough"
      - name: dropoff_borough
        description: "Dropoff Borough"
  - name: credit_cart_count
    description: "Breakdown of count of fares paid by credit card"
    columns:
      - name: total_count
        description: "Count of records paid by credit card"
      - name: fare_amt
        description: "Sum of fares paid by credit card"
      - name: payment
        description: "Payment type"
  - name: cross_borough
    description: "Trips that started in one borough and ended in another"
    columns:
      - name: pickup
        description: "Pickup Time"
      - name: dropoff
        description: "Dropoff Time"
      - name: passengers
        description: "Number of Passangers"
      - name: distance
        description: "Distance"
      - name: fare
        description: "Fare"
      - name: tip
        description: "Tip"
      - name: tolls
        description: "Tolls"
      - name: total
        description: "Total"
      - name: color
        description: "Color"
      - name: payment
        description: "Payment Method"
      - name: pickup_zone
        description: "Pickup Zone"
      - name: dropoff_zone
        description: "Dropoff Zone"
      - name: pickup_borough
        description: "Pickup Borough"
      - name: dropoff_borough
        description: "Dropoff Borough"
  - name: avg_num_dropoff_manhattan
    description: "Average # of passengers per trip ending in Manhattan"
    columns:
      - name: avg_passengers
        description: "Average # of passengers"
      - name: dropoff_borough
        description: "The dropoff borough (in Manhattan)"
  
  